In [1]:
import numpy as np

In [2]:
X = np.array([[1,1,1,1,1,1],[-1,-1,-1,-1,-1,-1],[1,-1,-1,1,1,1],[1,1,-1,-1,-1,-1]])
y=np.array([[1,1,1],[-1,-1,-1],[-1,1,1],[1,-1,1]])

In [3]:
def _init_(n, m):
    w = np.zeros((m, n))
    return w

In [4]:
def transmission_function(z):
    for i in range(z.shape[0]):
        if z[i] > 1:
            z[i] = 1
        elif z[i] < -1:
            z[i] = -1
        else:
            z[i] = 0
    return z

In [20]:
def bam_algorithm(X, y, w, lr, beta, leraningRateFlag):
    v = w.T
    flag = True
    epoch = 0
    while (flag):
        flag = False
        for i in range(X.shape[0]):
            y_pred = np.dot(X[i], w.T) 
            x_pred = np.dot(y[i], v.T)
            x_pred = transmission_function(x_pred)
            y_pred = transmission_function(y_pred)
            
            #Feed forward - Calculating target values...................................
            if(np.array_equal(y_pred, y[i]) == False):
                flag = True
                xi_pred = np.atleast_2d(x_pred)
                yi_pred = np.atleast_2d(y_pred)
                yi = np.atleast_2d(y[i])
                xi = np.atleast_2d(X[i])
                w = (beta * w) + (lr * np.dot((yi - yi_pred).T, (xi + xi_pred)))
             
            #Feed forward - Calculating input values....................................
            if(np.array_equal(x_pred, X[i])==False):
                xi_pred = np.atleast_2d(transmission_function(x_pred))
                yi_pred = np.atleast_2d(transmission_function(y_pred))
                yi = np.atleast_2d(y[i])
                xi = np.atleast_2d(X[i])
                flag = True
                v = (beta * v) + (lr * np.dot((xi - xi_pred).T, (yi+yi_pred)))
            
            #Updating learning rate.....................................................
            if leraningRateFlag:
                lr = 1 / ((1 - 2 * 0.2)*max(X.shape[1], y.shape[1]))
            epoch = epoch +1
    print("Weights Convereged After ",epoch," Epochs......")
    return w, v, epoch
    

In [23]:
w = _init_(X.shape[1], y.shape[1])
[w, v, e] = bam_algorithm(X, y, w, 0.1, 1, True) #True - Modified Learning Rate else false

Weights Convereged After  24  Epochs......


In [24]:
#Finding target values using calculated w weight matrix
for i in range(X.shape[0]):
    y_pred = np.dot(X[i], w.T)
    y_pred = transmission_function(y_pred)
    print(y_pred)

[1. 1. 1.]
[-1. -1. -1.]
[-1.  1.  1.]
[ 1. -1.  1.]


In [25]:
#Finding input values using calculated v weight matrix
for i in range(y.shape[0]):
    x_pred = np.dot(y[i], v.T)
    x_pred = transmission_function(x_pred)
    print(x_pred)

[1. 1. 1. 1. 1. 1.]
[-1. -1. -1. -1. -1. -1.]
[ 1. -1. -1.  1.  1.  1.]
[ 1.  1. -1. -1. -1. -1.]
